version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  # Build and deploy laravel api files
  transfer_to_server:
    docker:
      - image: cimg/php:8.3.2
    steps:
      - checkout
      - run:
          name: Deploy api via FTP
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp
            lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./ /; bye"
workflows:
  version: 2
  deploy:
    jobs:
      - transfer_to_server

#lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./cardCraft-front/dist/spa /public; bye"
#            lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./cardCraft-api /api; bye"

